name: Generate Devvit Fixtures and DB

on:
  schedule:
    - cron: '0 21 * * *'
  workflow_dispatch:
  pull_request:

jobs:
  generate:
    runs-on: ubuntu-latest

    permissions:
      # Give the default GITHUB_TOKEN write permission to commit and push the
      # added or changed files to the repository.
      contents: write
      pull-requests: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          # Use the version declared in .nvmrc if present; otherwise default to 20.x
          node-version-file: '.nvmrc'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Generate chunks
        run: npm run scripts:generate-chunks

      - name: Generate SQLite DB
        run: npm run scripts:generate-sqlite-db

      - name: Get current date
        id: date
        run: echo "date=$(date +'%Y-%m-%d')" >> $GITHUB_OUTPUT

      - name: Create release tag
        id: create_tag
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          # Check if the tag already exists remotely or locally
          if git rev-parse "refs/tags/${{ steps.date.outputs.date }}" >/dev/null 2>&1 || \
             git ls-remote --tags origin | grep -q "refs/tags/${{ steps.date.outputs.date }}$"; then
            echo "Tag ${{ steps.date.outputs.date }} already exists. Skipping tag creation."
          else
            git tag ${{ steps.date.outputs.date }}
            git push origin ${{ steps.date.outputs.date }}
          fi

      - name: Create GitHub Release
        id: create_release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ steps.date.outputs.date }}
          name: Release ${{ steps.date.outputs.date }}
          body: 'Automated release for ${{ steps.date.outputs.date }}'
          draft: false
          prerelease: false
          files: |
            db/devvit-docs.db
            fixtures.tar.gz
